apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
- path: application-controller-patch.yaml
  target:
    kind: StatefulSet
    name: argocd-application-controller
- path: argocd-cm-patch.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
